{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.vvb2060.ndk",
    "module": "curl",
    "version": "7.88.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.vvb2060.ndk",
          "module": "boringssl",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "curl-7.88.1-SNAPSHOT.aar",
          "url": "curl-7.88.1-SNAPSHOT.aar",
          "size": 21144874,
          "sha512": "e761168164d7894917e6937b367366b26a711519685c303fbe2ffab9b3d24fe6a1d2d533af4c62efce44a42a85c1deb019992a2a2b6c82511c21b0d85adb3546",
          "sha256": "2a544109ad9883935ddbd0b901fe38bc32dbf77d1cf0eb6ecbc6366eb19a237c",
          "sha1": "e12572ce6fe1b418cfa7ef315cab824d8588baf8",
          "md5": "32edd8587a4305aabb836830aa397095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.vvb2060.ndk",
          "module": "boringssl",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "curl-7.88.1-SNAPSHOT.aar",
          "url": "curl-7.88.1-SNAPSHOT.aar",
          "size": 21144874,
          "sha512": "e761168164d7894917e6937b367366b26a711519685c303fbe2ffab9b3d24fe6a1d2d533af4c62efce44a42a85c1deb019992a2a2b6c82511c21b0d85adb3546",
          "sha256": "2a544109ad9883935ddbd0b901fe38bc32dbf77d1cf0eb6ecbc6366eb19a237c",
          "sha1": "e12572ce6fe1b418cfa7ef315cab824d8588baf8",
          "md5": "32edd8587a4305aabb836830aa397095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "curl-7.88.1-SNAPSHOT-sources.jar",
          "url": "curl-7.88.1-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "curl-7.88.1-SNAPSHOT-javadoc.jar",
          "url": "curl-7.88.1-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
